#!/bin/bash

echo debian:debian | chpasswd

if [ -n "${DIB_XTESTINGCI_VERSION}" ]; then
  LC_ALL=en_US.UTF-8 ansible-galaxy install -p /usr/share/ansible/roles collivier.xtesting,${DIB_XTESTINGCI_VERSION}
else
  LC_ALL=en_US.UTF-8 ansible-galaxy install -p /usr/share/ansible/roles collivier.xtesting
fi
LC_ALL=en_US.UTF-8 ansible-galaxy collection install -p /usr/share/ansible/collections \
  ansible.posix community.general community.grafana \
  community.kubernetes community.docker community.postgresql \
  community.crypto

cp /usr/share/ansible/roles/collivier.xtesting/tests/jenkins.yml /home/debian
echo "      deps_only: true" >> /home/debian/jenkins.yml
LC_ALL=en_US.UTF-8 ansible-playbook -vvv /home/debian/jenkins.yml
rm /home/debian/jenkins.yml

mkdir -p /data/docker/xtestingci
wget https://raw.githubusercontent.com/moby/moby/master/contrib/download-frozen-image-v2.sh \
  -O /usr/local/bin/download-frozen-image-v2.sh
chmod a+x /usr/local/bin/download-frozen-image-v2.sh
download-frozen-image-v2.sh /data/docker/xtestingci \
  opnfv/xtesting-jenkins:lts-slim \
  mongo:6.0 \
  opnfv/xtesting-s3www:v0.5.3 \
  minio/minio:RELEASE.2023-01-18T04-36-38Z \
  opnfv/testapi:kali \
  nginx:1.25

exit 0
