---
- name: Starting InfluxDB
  become: "{{ ansible_connection is defined }}"
  community.docker.docker_container:
    name: influxdb
    image: '{{ influxdb_docker_image }}:{{ influxdb_docker_tag }}'
    pull: '{{ docker_pull }}'
    recreate: '{{ docker_recreate }}'
    restart_policy: '{{ docker_restart_policy }}'
    published_ports:
      - '{{ influxdb_port }}:8086'
    volumes:
      - '{{ prefix }}/influxdb:/var/lib/influxdb'
    env:
      DOCKER_INFLUXDB_INIT_USERNAME: '{{ influxdb_username }}'
      DOCKER_INFLUXDB_INIT_PASSWORD: '{{ influxdb_password }}'
    container_default_behavior: no_defaults
  notify:
    - Waiting InfluxDB
  when:
    - influxdb_deploy
    - not use_kubernetes
- name: Adding InfluxDB chart repository
  kubernetes.core.helm_repository:
    name: influxdata
    repo_url: https://helm.influxdata.com/
  when:
    - influxdb_deploy
    - use_kubernetes
- name: Installing InfluxDB helm chart
  kubernetes.core.helm:
    name: influxdata
    chart_ref: influxdata/influxdb2
    chart_version: 2.0.4
    release_namespace: default
    values:
      image:
        repository: '{{ influxdb_docker_image }}'
        tag: '{{ influxdb_docker_tag }}'
      adminUser:
        user: '{{ influxdb_username }}'
        password: '{{ influxdb_password }}'
      service:
        type: NodePort
        nodePort: '{{ influxdb_port }}'
    wait: true
  notify:
    - Waiting InfluxDB
  when:
    - influxdb_deploy
    - use_kubernetes
