---
- name: Starting MongoDB
  become: "{{ ansible_connection is defined }}"
  community.docker.docker_container:
    name: mongo
    image: '{{ mongo_docker_image }}:{{ mongo_docker_tag }}'
    pull: '{{ docker_pull }}'
    recreate: '{{ docker_recreate }}'
    restart_policy: '{{ docker_restart_policy }}'
    published_ports:
      - '{{ mongo_port }}:27017'
    volumes:
      - '{{ prefix }}/mongodb:/data/db'
    container_default_behavior: no_defaults
  notify:
    - Waiting MongoDB
  when:
    - mongo_deploy
    - not use_kubernetes
- name: Adding MongoDB chart repository
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami
  when:
    - mongo_deploy
    - use_kubernetes
- name: Installing MongoDB helm chart
  kubernetes.core.helm:
    name: mongo
    chart_ref: bitnami/mongodb
    chart_version: 10.30.6
    release_namespace: default
    values:
      image:
        repository: '{{ mongo_k8s_image }}'
        tag: '{{ mongo_k8s_tag }}'
      auth:
        enabled: false
      service:
        type: NodePort
        nodePort: '{{ mongo_port }}'
    wait: true
  notify:
    - Waiting MongoDB
  when:
    - mongo_deploy
    - use_kubernetes
- name: Flushing handlers
  meta: flush_handlers
