---
- name: Creating /etc/containers/registries.conf
  become: true
  ansible.builtin.copy:
    src: registries.conf
    dest: /etc/containers/registries.conf
    mode: '0644'
  when:
    - use_podman
- name: Marking / as shared
  become: true
  ansible.builtin.shell:
    cmd: mount --make-rshared /
  tags:
    - skip_ansible_lint
  when:
    - use_podman
    - ansible_module_running_in_container
