---
- name: Creating /etc/containers/registries.conf
  become: true
  ansible.builtin.copy:
    src: registries.conf
    dest: /etc/containers/registries.conf
    mode: '0644'
  when:
    - use_podman
