---
jenkins_port: 8080
minio_port: 9000
s3www_port: 80
testapi_port: 8000
registry_port: 5000
jenkins_user: admin
jenkins_password: admin
project: xtesting
gerrit: gerrit.opnfv.org
gerrit_project: functest-xtesting
slave:
block_level_key: block-level
sudo1:
use_testapi: true
use_jenkins: true
jenkins_workspace: /data/jenkins/workspace
publish:
  db: true
  cmd: mc cp -r
  repo: minio/{{ project }}
  www: http://127.0.0.1
docker_tags:
docker_args:
  env: {}
  volumes: []
triggers:
  - timed: '@daily'
repo: opnfv
dport:
builds:
  dependencies:
    - repo: _
      dport:
      container: alpine
      tag: 3.8
  steps:
    - name: opnfv/functest-xtesting
      containers:
        - name: xtesting
          ref_arg: BRANCH
          path: docker
suites:
  - container: xtesting
    tests:
      - first
      - second
      - third
      - fourth
      - fifth
