---
- name: Restarting Docker
  become: true
  ansible.builtin.service:
    name: docker
    state: restarted
  notify:
    - Pausing 10 seconds
- name: Pausing 10 seconds
  ansible.builtin.pause:
    seconds: 10
- name: Waiting Jenkins
  ansible.builtin.uri:
    url: "{{ jenkins_url }}"
    user: "{{ jenkins_user }}"
    password: "{{ jenkins_password }}"
    force_basic_auth: true
    method: GET
  register: _result
  until: _result.status == 200
  retries: "{{ ((jenkins_wait | int) / 5) | int }}"
  delay: 5
- name: Waiting Cachet
  ansible.builtin.uri:
    url: "{{ cachet_url }}/ping"
    method: GET
  register: _result
  until: _result.status == 200
  retries: "{{ ((cachet_wait | int) / 5) | int }}"
  delay: 5
- name: Waiting MongoDB
  ansible.builtin.pause:
    seconds: '{{ mongo_wait }}'
- name: Waiting Kibana
  ansible.builtin.pause:
    seconds: '{{ kibana_wait }}'
- name: Waiting Grafana
  ansible.builtin.uri:
    url: "{{ grafana_url }}/api/health"
    method: GET
  register: _result
  until: _result.status == 200
  retries: "{{ ((grafana_wait | int) / 5) | int }}"
  delay: 5
- name: Waiting Fluentd
  ansible.builtin.pause:
    seconds: "{{ fluentd_wait }}"
- name: Waiting PostgreSQL
  community.postgresql.postgresql_query:
    db: '{{ postgres_database }}'
    login_host: '{{ postgres_host }}'
    login_port: '{{ postgres_port }}'
    login_user: '{{ postgres_username }}'
    login_password: '{{ postgres_database }}'
    query: SELECT version()
  register: _result
  until: ("rowcount" in _result and _result.rowcount | int >= 1)
  retries: "{{ ((postgres_wait | int) / 5) | int }}"
  delay: 5
- name: Waiting Elasticsearch
  ansible.builtin.pause:
    seconds: '{{ elasticsearch_wait }}'
- name: Waiting GitLab
  ansible.builtin.uri:
    url: "{{ gitlab_url }}"
    method: GET
  register: _result
  until: _result.status == 200
  retries: "{{ ((gitlab_wait | int) / 5) | int }}"
  delay: 5
- name: Waiting TestAPI
  ansible.builtin.uri:
    url: "{{ testapi_url }}/results"
    method: GET
  register: _result
  until: _result.status == 200
  retries: "{{ ((testapi_wait | int) / 5) | int }}"
  delay: 5
- name: Waiting Gitea
  ansible.builtin.uri:
    url: "{{ gitea_url }}"
    method: GET
  register: _result
  until: _result.status == 200
  retries: "{{ ((gitea_wait | int) / 5) | int }}"
  delay: 5
- name: Waiting Nexus
  ansible.builtin.uri:
    url: "{{ nexus_url }}/service/rest/v1/status"
    method: GET
  register: _result
  until: _result.status == 200
  retries: "{{ ((nexus_wait | int) / 5) | int }}"
  delay: 5
- name: Waiting InfluxDB
  ansible.builtin.uri:
    url: "{{ influxdb_url }}/ping"
    method: GET
    status_code: 204
  register: _result
  until: _result.status == 204
  retries: "{{ ((influxdb_wait | int) / 5) | int }}"
  delay: 5
